# Generated by Django 5.0.2 on 2024-02-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Blog Posts'},
        ),
    ]
